services:
  - type: web
    name: c-next
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn project.wsgi:application
    plan: free

